// Create web server 

var express = require('express');
var app = express();
var myParser = require("body-parser");
var fs = require('fs');
var qs = require('qs');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var nodemailer = require('nodemailer');
var products = require('./public/products.js');
var services = require('./public/services.js');
var user_data = require('./user_data.json');
var userdatafile = './user_data.json';
var filename = 'user_data.json';
var quantity_str;
var quantity_str2;
var quantity_str3;
var quantity_str4;
var quantity_str5;
var quantity_str6;
var quantity_str7;
var quantity_str8;
var quantity_str9;
var quantity_str10;
var quantity_str11;
var quantity_str12;
var quantity_str13;
var quantity_str14;
var quantity_str15;
var quantity_str16;
var quantity_str17;
var quantity_str18;
var quantity_str19;
var quantity_str20;
var quantity_str21;
var quantity_str22;
var quantity_str23;
var quantity_str24;
var quantity_str25;
var quantity_str26;
var quantity_str27;
var quantity_str28;
var quantity_str29;
var quantity_str30;
var quantity_str31;
var quantity_str32;
var quantity_str33;
var quantity_str34;
var quantity_str35;
var quantity_str36;
var quantity_str37;
var quantity_str38;
var quantity_str39;
var quantity_str40;
var quantity_str41;
var quantity_str42;
var quantity_str43;
var quantity_str44;
var quantity_str45;
var quantity_str46;
var quantity_str47;
var quantity_str48;
var quantity_str49;
var quantity_str50;
var quantity_str51;
var quantity_str52;
var quantity_str53;
var quantity_str54;
var quantity_str55;
var quantity_str56;
var quantity_str57;
var quantity_str58;
var quantity_str59;
var quantity_str60;
var quantity_str61;
var quantity_str62;
var quantity_str63;
var quantity_str64;
var quantity_str65;
var quantity_str66;
var quantity_str67;
var quantity_str68;
var quantity_str69;
var quantity_str70;
var quantity_str71;
var quantity_str72;
var quantity_str73;
var quantity_str74;
var quantity_str75;
var quantity_str76;
var quantity_str77;
var quantity_str78;
var quantity_str79